### ISSUE TITLE
새로 도출한 사항을 가지고 자판기 미션을 진행한뒤, 느낀점을 공유한다.

### ISSUE THREAD

**Issue by unluckyjung** [woowacourse/java-vendingmachine#7]
추가된 사항이 어떤 메시지를 담고 있는지 이야기해본다.

- 날짜 : 06.01(화) 16:00 1번 회의실

**Comment by Joyykim** [comment]
https://github.com/woowacourse/service-issues/wiki/%5B2021-06-01%5D-%EC%9E%90%ED%8C%90%EA%B8%B0-%EB%AF%B8%EC%85%98%EC%97%90-%EB%8C%80%ED%95%9C-%EC%B6%94%EA%B0%80-%EA%B8%B0%EB%8A%A5-%EC%9A%94%EA%B5%AC-%EC%82%AC%ED%95%AD-%EB%8F%84%EC%B6%9C-%ED%9A%8C%EC%9D%98
